# Generated by Django 3.1 on 2020-12-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201228_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listt',
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
