# Generated by Django 3.1 on 2020-12-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201228_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, default=None, help_text='UserAccount first name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, help_text='UserAccount last name', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=40)),
                ('age', models.IntegerField(verbose_name='age')),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.useraccount'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
