# Generated by Django 3.1 on 2020-12-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201228_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='listt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.list'),
        ),
    ]
