# Generated by Django 3.1 on 2020-12-29 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201228_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 18, 7, 20, 58862)),
        ),
    ]
